//! The CLI reference page, walked from the clap definition of `b10x-llm-gateway`
//! (`llm_gateway_cli::cli::Cli`). The binary has no subcommand, so the page lists the root's
//! arguments.

use std::fmt::Write as _;

use clap::CommandFactory as _;

use crate::{GITHUB, cell, front_matter};

/// Where the CLI reference lands, relative to the repository root.
pub const PAGE: &str = "website/docs/reference/cli.md";

fn text(value: Option<&clap::builder::StyledStr>) -> String {
    value.map(ToString::to_string).unwrap_or_default()
}

/// One row per argument of `command`: how it is written, whether it is required, its default
/// and its help.
fn arguments(command: &clap::Command) -> Vec<[String; 4]> {
    command
        .get_arguments()
        .filter(|arg| !matches!(arg.get_id().as_str(), "help" | "version"))
        .map(|arg| {
            let value = arg
                .get_value_names()
                .and_then(|names| names.first().map(ToString::to_string))
                .unwrap_or_else(|| arg.get_id().as_str().to_uppercase());
            let takes_value = arg.get_num_args().is_some_and(|n| n.takes_values());
            let written = match (arg.get_long(), takes_value) {
                (Some(long), true) => format!("--{long} <{value}>"),
                (Some(long), false) => format!("--{long}"),
                (None, _) => format!("<{value}>"),
            };
            let defaults: Vec<String> = arg
                .get_default_values()
                .iter()
                .map(|default| default.to_string_lossy().into_owned())
                .filter(|default| default != "false")
                .collect();
            let mut help = cell(&text(arg.get_long_help().or(arg.get_help())));
            if !help.is_empty() && !help.ends_with('.') {
                help.push('.');
            }
            [
                format!("`{written}`"),
                if arg.is_required_set() { "yes" } else { "no" }.to_owned(),
                if defaults.is_empty() {
                    "none".to_owned()
                } else {
                    format!("`{}`", defaults.join(", "))
                },
                help,
            ]
        })
        .collect()
}

/// The CLI reference page for the command line `root`.
pub fn page_for(mut root: clap::Command) -> String {
    root.build();
    let name = root.get_name().to_owned();
    let mut out = front_matter(
        &format!("{name} command line"),
        1,
        &format!("Every option of the {name} command line, generated from its clap definition."),
    );
    let _ = write!(
        out,
        "# `{name}`\n\nGenerated by `llm-gateway-docs` from the clap definition in \
         [`crates/llm-gateway-cli/src/cli.rs`]({GITHUB}/blob/main/crates/llm-gateway-cli/src/cli.rs). \
         `{name} --help` prints the same text and `{name} --version` prints the name and the \
         package version.\n\n> {}\n\n```text\n{}\n```\n\n\
         ## Options\n\n| Option | Required | Default | Meaning |\n| --- | --- | --- | --- |\n",
        cell(&text(root.get_long_about().or(root.get_about()))),
        root.render_usage().to_string().trim_end(),
    );
    for row in arguments(&root) {
        let _ = writeln!(out, "| {} |", row.join(" | "));
    }
    out.push_str(
        "\nThe command line takes nothing else: a subcommand, a positional argument or another \
         option is a usage error. The document the option names is described in \
         [the deployment document](./deployment-document.md).\n\n\
         ## Exit status\n\n| Status | When | Last line on standard error |\n| --- | --- | --- |\n\
         | 0 | stopped by SIGINT or SIGTERM after every accepted request was answered | \
         `b10x-llm-gateway: stopped by <signal> accepted=<n> completed=<n>` |\n\
         | 1 | the start was refused: the document, a file it names, the listen address or the \
         signal handlers | `b10x-llm-gateway: refused <source>:<rule>: <message>` |\n\
         | 2 | a usage error, reported by clap | clap's usage message |\n\n\
         While it serves, the process writes `b10x-llm-gateway: listening on <address>` once. \
         `RUST_LOG` sets the level of the structured events it writes beside these lines \
         (default `info`).\n",
    );
    out
}

/// The CLI reference page for `b10x-llm-gateway`.
pub fn page() -> String {
    page_for(llm_gateway_cli::cli::Cli::command())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_one_option_and_the_usage_line_are_listed() {
        let page = page();
        assert!(page.contains(crate::HEADER));
        assert!(page.contains("custom_edit_url: null"));
        assert!(page.contains("Usage: b10x-llm-gateway --config <CONFIG>"));
        assert!(page.contains("| `--config <CONFIG>` | yes | none |"));
        assert!(!page.contains("`--help`"), "help and version are not rows");
    }
}
