//! Generates the derivable pages of the llm-gateway documentation site, checks them and the
//! hand-written pages for drift, and binds a built site to its source commit and lists its
//! routes. The site build itself is Docusaurus.
//!
//! Five files are generated:
//!
//! - `website/docs/reference/cli.md`, from the clap definition `llm_gateway_cli::cli::Cli`;
//! - `website/docs/reference/crates.md`, from `cargo metadata --no-deps`;
//! - `website/docs/reference/refusals.md`, from `llm_gateway::RefusalCode::ALL`;
//! - `website/data/status.json` (`b10x-status/1`) and `website/docs/status.mdx`, from the
//!   capability list in `status.rs`, whose every shipped item names the test that holds it.
//!
//! `generate --check` also checks the hand-written pages: no raw admonition title, no story id
//! and no home-directory path.

mod cli;
mod crates;
mod pages;
mod refusals;
mod routes;
mod status;

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::ExitCode,
};

use clap::{Parser, Subcommand};

/// Every failure is reported as one message and exit code 1.
pub type Result<T> = std::result::Result<T, String>;

/// The line every generated Markdown page carries directly after its front matter.
pub const HEADER: &str = "<!-- generated by llm-gateway-docs, do not edit -->";
/// The same line in an MDX page, where HTML comments are not allowed.
pub const MDX_HEADER: &str = "{/* generated by llm-gateway-docs, do not edit */}";
/// Every documentation page, relative to the repository root.
pub const DOCS: &str = "website/docs";
/// The repository on GitHub, for links into its files.
pub const GITHUB: &str = "https://github.com/beyond10x/llm-gateway";

#[derive(Parser)]
#[command(about = "Generate and check the derived pages of the llm-gateway documentation site")]
struct Cli {
    #[command(subcommand)]
    command: Action,
}

#[derive(Subcommand)]
enum Action {
    /// Regenerate the references and the status page, or check them for drift.
    Generate {
        /// Write nothing; fail when a generated file is missing, stale or hand-edited.
        #[arg(long)]
        check: bool,
        /// Repository root.
        #[arg(long, default_value = ".")]
        root: PathBuf,
    },
    /// Bind a built site to its source commit: write `.well-known/b10x-site.json` and the route
    /// inventory `.well-known/b10x-routes.json` into it.
    Provenance {
        /// The built site, `website/build`.
        #[arg(long)]
        site: PathBuf,
        /// The full Git revision the site was built from.
        #[arg(long)]
        commit: String,
    },
}

/// Generated files keyed by their path relative to the repository root.
type Outputs = BTreeMap<&'static str, String>;

fn outputs(root: &Path) -> Result<Outputs> {
    let crates = crates::page(&crates::metadata(root)?)?;
    let record = status::record(root)?;
    Ok(Outputs::from([
        (cli::PAGE, cli::page()),
        (crates::PAGE, crates),
        (refusals::PAGE, refusals::page()),
        (status::DATA, status::data(&record)),
        (status::PAGE, status::page(&record)),
    ]))
}

/// The drift of one generated file: `None` when it is current.
fn drift(root: &Path, relative: &str, expected: &str) -> Option<String> {
    match fs::read_to_string(root.join(relative)) {
        Err(_) => Some(format!("missing {relative}")),
        Ok(found) if found != expected => Some(format!("stale or edited {relative}")),
        Ok(_) => None,
    }
}

fn generate(root: &Path, check: bool) -> Result<()> {
    let outputs = outputs(root)?;
    if check {
        let problems: Vec<_> = outputs
            .iter()
            .filter_map(|(relative, content)| drift(root, relative, content))
            .collect();
        if !problems.is_empty() {
            return Err(format!(
                "generated files have drifted ({}); run `cargo run --locked -p llm-gateway-docs -- generate`",
                problems.join(", ")
            ));
        }
        for relative in outputs.keys() {
            println!("{relative}: current");
        }
    } else {
        for (relative, content) in &outputs {
            let path = root.join(relative);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("creating {}: {error}", parent.display()))?;
            }
            fs::write(&path, content).map_err(|error| format!("writing {relative}: {error}"))?;
            println!("{relative}: written");
        }
    }
    let problems = pages::check(root)?;
    if !problems.is_empty() {
        return Err(format!(
            "hand-written pages fail their checks:\n  {}",
            problems.join("\n  ")
        ));
    }
    println!("{DOCS}: no raw admonition title, story id or home-directory path");
    Ok(())
}

/// The project-site publication record for one build of the `/llm-gateway/` site.
fn site_manifest(commit: &str) -> Result<String> {
    if commit.len() != 40
        || !commit.bytes().all(|b| b.is_ascii_hexdigit())
        || commit.bytes().all(|b| b == b'0')
    {
        return Err("commit must be a nonzero full Git revision".to_owned());
    }
    Ok(format!(
        "{{\n  \"baseUrl\": \"{}\",\n  \"commit\": \"{commit}\",\n  \"repository\": \"llm-gateway\",\n  \"schema\": \"b10x-project-site/v1\"\n}}",
        routes::BASE
    ))
}

fn write_provenance(site: &Path, commit: &str) -> Result<()> {
    let manifest = site_manifest(commit)?;
    if !site.join("index.html").is_file() {
        return Err(format!("{} holds no built site", site.display()));
    }
    let inventory = routes::inventory(site, commit)?;
    let write = |path: PathBuf, content: &str| {
        fs::write(&path, content).map_err(|error| format!("writing {}: {error}", path.display()))
    };
    fs::create_dir_all(site.join(".well-known"))
        .map_err(|error| format!("creating .well-known: {error}"))?;
    write(site.join(".well-known/b10x-site.json"), &manifest)?;
    write(site.join(".well-known/b10x-routes.json"), &inventory)?;
    write(site.join(".nojekyll"), "")
}

fn main() -> ExitCode {
    let result = match Cli::parse().command {
        Action::Generate { check, root } => generate(&root, check),
        Action::Provenance { site, commit } => write_provenance(&site, &commit)
            .map(|()| println!("{}: bound to {commit}", site.display())),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("llm-gateway-docs: {message}");
            ExitCode::FAILURE
        }
    }
}

/// Quote a value as a YAML double-quoted scalar.
pub(crate) fn yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

/// Text made safe for one Markdown table cell.
pub(crate) fn cell(value: &str) -> String {
    value
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}

/// The front matter and header of a generated Markdown page.
pub(crate) fn front_matter(title: &str, position: u32, description: &str) -> String {
    format!(
        "---\ntitle: {}\nsidebar_position: {position}\ndescription: {}\ncustom_edit_url: null\n---\n\n{HEADER}\n\n",
        yaml_string(title),
        yaml_string(description),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provenance_refuses_anything_but_a_full_nonzero_revision() {
        let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
        assert!(site_manifest(commit).unwrap().contains(commit));
        for bad in [
            "e86f43d",
            &"0".repeat(40),
            &format!("{}\"", &commit[..39]),
            &format!("{commit}0"),
        ] {
            assert!(site_manifest(bad).is_err(), "{bad}");
        }
    }

    #[test]
    fn yaml_strings_escape_quotes_and_backslashes() {
        assert_eq!(yaml_string(r#"a "b" \c"#), r#""a \"b\" \\c""#);
    }

    #[test]
    fn a_cell_is_one_line_with_its_pipes_escaped() {
        assert_eq!(cell("a |\n  b"), "a \\| b");
    }
}
