//! The refusal reference, from `llm_gateway::RefusalCode::ALL`: every code the gateway can emit,
//! with the status and the fixed message the code itself returns, and every startup refusal of the
//! binary, from `llm_gateway_cli::StartupRefusal::ALL`.

use std::fmt::Write as _;

use llm_gateway::RefusalCode;
use llm_gateway_cli::StartupRefusal;

use crate::{GITHUB, front_matter};

/// Where the refusal reference lands, relative to the repository root.
pub const PAGE: &str = "website/docs/reference/refusals.md";

/// The refusal reference page.
pub fn page() -> String {
    let mut codes = RefusalCode::ALL.to_vec();
    codes.sort_by_key(|code| code.wire());
    let mut out = front_matter(
        "Refusals",
        3,
        "Every refusal code the gateway can answer, with its HTTP status and its fixed message.",
    );
    let _ = write!(
        out,
        "# Refusals\n\nA refusal is one JSON object naming a stable code and a message the gateway \
         wrote. It quotes nothing the caller sent: a rejected credential is never echoed back, and \
         no upstream text reaches a refusal. A model's own answer, a `500` or a `4xx` from the \
         target included, is relayed, not refused.\n\n\
         ```json\n{{\"error\":{{\"code\":\"credential-absent\",\"message\":\"no owner credential was presented\"}}}}\n```\n\n\
         This page is generated by `llm-gateway-docs` from `RefusalCode::ALL` in \
         [`crates/llm-gateway/src/error.rs`]({GITHUB}/blob/main/crates/llm-gateway/src/error.rs). \
         The gateway's tests check the same set against the contract \
         [`docs/gateway.md`]({GITHUB}/blob/main/docs/gateway.md#refusals) and provoke every code \
         with a request. Every `401` carries `www-authenticate: Bearer`, every `405` an `allow` \
         header, and only `model-cold-start` carries `retry-after` (30 seconds).\n\n\
         | Code | Status | Message |\n| --- | --- | --- |\n"
    );
    for code in codes {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            code.wire(),
            code.status(),
            code.reason()
        );
    }
    let _ = write!(
        out,
        "\n## Startup refusals\n\nBefore it serves, the binary refuses a start with one line on \
         standard error, `b10x-llm-gateway: refused <code>: <message>`, and exit status 1. The \
         code is `<source>:<rule>`. This list is generated from `StartupRefusal::ALL` in \
         [`crates/llm-gateway-cli/src/refusal.rs`]({GITHUB}/blob/main/crates/llm-gateway-cli/src/refusal.rs); \
         [the deployment document](./deployment-document.md) says which rule each file and key \
         must keep.\n\n| Startup code |\n| --- |\n"
    );
    for refusal in StartupRefusal::ALL {
        let _ = writeln!(out, "| `{}` |", refusal.code());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_code_is_one_row_in_code_order() {
        let page = page();
        let (gateway, startup) = page.split_once("## Startup refusals").unwrap();
        let rows: Vec<_> = gateway
            .lines()
            .filter(|line| line.starts_with("| `"))
            .collect();
        assert_eq!(rows.len(), RefusalCode::ALL.len());
        let startup_rows = startup.lines().filter(|line| line.starts_with("| `"));
        assert_eq!(startup_rows.count(), StartupRefusal::ALL.len());
        assert!(startup.contains("| `config:schema` |"));
        let mut sorted = rows.clone();
        sorted.sort_unstable();
        assert_eq!(rows, sorted);
        assert!(
            page.contains("| `tools-not-served` | 400 | the model does not serve tool calls |")
        );
    }
}
