//! Acceptance for `llm-gateway-docs`: the CLI, crate and refusal references and the status page
//! are generated from the code and the workspace, `generate --check` fails on any drift, the
//! hand-written pages keep the public boundary, and `provenance` binds a built site to its commit.
//!
//! Source files are read at run time through `CARGO_MANIFEST_DIR`, never baked in at compile
//! time, so a binary reused from another tree cannot read that tree's pages.

use std::{
    fs,
    path::{Path, PathBuf},
    process::{Command, Output},
};

use llm_gateway::RefusalCode;

const CLI_PAGE: &str = "website/docs/reference/cli.md";
const CRATES_PAGE: &str = "website/docs/reference/crates.md";
const REFUSALS_PAGE: &str = "website/docs/reference/refusals.md";
const STATUS_DATA: &str = "website/data/status.json";
const STATUS_PAGE: &str = "website/docs/status.mdx";
const GENERATED: [&str; 5] = [
    CLI_PAGE,
    CRATES_PAGE,
    REFUSALS_PAGE,
    STATUS_DATA,
    STATUS_PAGE,
];
const HEADER: &str = "<!-- generated by llm-gateway-docs, do not edit -->";
const MDX_HEADER: &str = "{/* generated by llm-gateway-docs, do not edit */}";
const COMMIT: &str = "e86f43d90b637fc2c1790f77d59efff2eb852386";

fn repository() -> PathBuf {
    let manifest = std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    Path::new(&manifest)
        .join("../..")
        .canonicalize()
        .expect("the repository root exists")
}

fn docs(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_llm-gateway-docs"))
        .args(args)
        .output()
        .expect("llm-gateway-docs runs")
}

fn text(bytes: &[u8]) -> String {
    String::from_utf8_lossy(bytes).into_owned()
}

fn read(root: &Path, relative: &str) -> String {
    fs::read_to_string(root.join(relative)).unwrap_or_else(|e| panic!("reading {relative}: {e}"))
}

fn scratch(name: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("llm-gateway-docs-{name}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    dir
}

/// Copy `from` into `to`, leaving out build output and installed packages.
fn copy_tree(from: &Path, to: &Path) {
    fs::create_dir_all(to).unwrap();
    for entry in fs::read_dir(from).unwrap() {
        let entry = entry.unwrap();
        let name = entry.file_name();
        if ["target", "node_modules", "build", ".docusaurus"]
            .iter()
            .any(|skip| name == *skip)
        {
            continue;
        }
        let path = entry.path();
        if path.is_dir() {
            copy_tree(&path, &to.join(&name));
        } else {
            fs::copy(&path, to.join(&name)).unwrap();
        }
    }
}

fn append(path: &Path, line: &str) {
    let mut content = fs::read_to_string(path).unwrap();
    content.push_str(line);
    fs::write(path, content).unwrap();
}

#[test]
fn check_passes_on_the_repository() {
    let root = repository();
    let out = docs(&["generate", "--check", "--root", root.to_str().unwrap()]);
    let stdout = text(&out.stdout);
    assert!(
        out.status.success(),
        "generate --check failed on the repository\nstdout: {stdout}\nstderr: {}",
        text(&out.stderr)
    );
    for file in GENERATED {
        assert!(stdout.contains(file), "check does not report {file}: {stdout}");
    }
}

#[test]
fn generated_pages_carry_the_generator_header() {
    let root = repository();
    for page in [CLI_PAGE, CRATES_PAGE, REFUSALS_PAGE] {
        let content = read(&root, page);
        assert!(content.contains(HEADER), "{page} lacks the header");
        assert!(
            content.contains("custom_edit_url: null"),
            "{page} is editable"
        );
    }
    let status = read(&root, STATUS_PAGE);
    assert!(status.contains(MDX_HEADER), "{STATUS_PAGE} lacks the header");
    assert!(status.contains("custom_edit_url: null"));
    assert!(status.contains("import status from '@site/data/status.json';"));
    assert!(status.contains("<StatusTable data={status} />"));
}

#[test]
fn cli_reference_is_the_binary_s_clap_definition() {
    let root = repository();
    let page = read(&root, CLI_PAGE);
    assert!(
        page.contains("Usage: b10x-llm-gateway --config <CONFIG>"),
        "{page}"
    );
    assert!(
        page.contains("| `--config <CONFIG>` | yes | none | Path to the closed TOML deployment document. |"),
        "{page}"
    );
    assert!(
        page.contains("The authenticated single-owner llm-gateway"),
        "the about text"
    );
    for status in ["| 0 |", "| 1 |", "| 2 |"] {
        assert!(page.contains(status), "exit status {status}: {page}");
    }
}

#[test]
fn refusal_reference_lists_every_code_the_gateway_can_emit() {
    let root = repository();
    let page = read(&root, REFUSALS_PAGE);
    let mut missing = Vec::new();
    for code in RefusalCode::ALL {
        let row = format!(
            "| `{}` | {} | {} |",
            code.wire(),
            code.status(),
            code.reason()
        );
        if !page.contains(&row) {
            missing.push(row);
        }
    }
    assert!(missing.is_empty(), "{REFUSALS_PAGE} lacks: {missing:?}");
    let rows = page.lines().filter(|line| line.starts_with("| `")).count();
    assert_eq!(rows, RefusalCode::ALL.len(), "one row per code, no other");
}

#[test]
fn crates_page_lists_every_workspace_package() {
    let root = repository();
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let out = Command::new(cargo)
        .args(["metadata", "--no-deps", "--format-version", "1", "--offline"])
        .arg("--manifest-path")
        .arg(root.join("Cargo.toml"))
        .output()
        .expect("cargo metadata runs");
    assert!(out.status.success(), "{}", text(&out.stderr));
    let metadata: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let page = read(&root, CRATES_PAGE);
    let packages = metadata["packages"].as_array().unwrap();
    assert!(packages.len() >= 7, "cargo metadata listed {}", packages.len());
    let mut missing = Vec::new();
    for package in packages {
        let name = package["name"].as_str().unwrap();
        if !page.contains(&format!("`{name}`")) {
            missing.push(format!("package {name}"));
        }
        if let Some(description) = package["description"].as_str()
            && !page.contains(description)
        {
            missing.push(format!("description of {name}"));
        }
    }
    assert!(missing.is_empty(), "{CRATES_PAGE} lacks: {missing:?}");
}

#[test]
fn status_marks_the_inert_runpod_relay_planned_and_names_tests_for_shipped_items() {
    let root = repository();
    let status: serde_json::Value = serde_json::from_str(&read(&root, STATUS_DATA)).unwrap();
    assert_eq!(status["format"], "b10x-status/1");
    assert!(status["asOf"].as_str().is_some_and(|d| d.len() == 10));
    let items = status["items"].as_array().unwrap();
    let count = |wanted: &str| {
        items
            .iter()
            .filter(|item| item["status"] == wanted)
            .count()
    };
    assert!(count("shipped") >= 10, "shipped: {}", count("shipped"));
    assert!(count("planned") >= 3, "planned: {}", count("planned"));
    for item in items {
        for key in ["area", "label", "detail", "status"] {
            assert!(
                item[key].as_str().is_some_and(|value| !value.is_empty()),
                "{key} of {item}"
            );
        }
        assert!(
            !item.to_string().contains("story:"),
            "a story id reached the status data: {item}"
        );
    }
    let relay = items
        .iter()
        .find(|item| {
            item["label"]
                .as_str()
                .is_some_and(|label| label.contains("Relay to a Runpod pod"))
        })
        .expect("the Runpod relay is listed");
    assert_eq!(relay["status"], "planned", "the binary refuses connectors");
}

#[test]
fn check_fails_on_every_kind_of_drift() {
    let root = repository();
    let tree = scratch("drift");
    for file in ["Cargo.toml", "Cargo.lock"] {
        fs::copy(root.join(file), tree.join(file)).unwrap();
    }
    for dir in ["crates", "checks", "website/docs", "website/data"] {
        copy_tree(&root.join(dir), &tree.join(dir));
    }
    let at = tree.to_str().unwrap();
    let check = || docs(&["generate", "--check", "--root", at]);
    let first = check();
    assert!(
        first.status.success(),
        "check on the copy: {}",
        text(&first.stderr)
    );

    // A hand edit and a missing file each fail the check, naming the file.
    for (file, remove) in [
        (CLI_PAGE, false),
        (CRATES_PAGE, false),
        (REFUSALS_PAGE, false),
        (STATUS_PAGE, false),
        (STATUS_DATA, true),
    ] {
        if remove {
            fs::remove_file(tree.join(file)).unwrap();
        } else {
            append(&tree.join(file), "Edited by hand.\n");
        }
        let out = check();
        assert!(!out.status.success(), "check passed after changing {file}");
        assert!(text(&out.stderr).contains(file), "{file}: {}", text(&out.stderr));
        let generate = docs(&["generate", "--root", at]);
        assert!(generate.status.success(), "{}", text(&generate.stderr));
        assert!(check().status.success(), "regenerate after {file}");
    }

    // A hand-written page that names a story, a home directory or a raw admonition title fails.
    let guide = tree.join("website/docs/getting-started.md");
    let original = fs::read_to_string(&guide).unwrap();
    for line in [
        "See story:docs-site.\n",
        // Assembled so the source carries no home path for the repository's own path scan.
        concat!("Built in /", "home", "/someone/llm-gateway.\n"),
        ":::caution Planned\n",
    ] {
        append(&guide, line);
        let out = check();
        assert!(!out.status.success(), "check passed with {line:?}");
        assert!(
            text(&out.stderr).contains("getting-started.md"),
            "{line:?}: {}",
            text(&out.stderr)
        );
        fs::write(&guide, &original).unwrap();
    }

    // A shipped capability whose test is gone fails generation, naming the test.
    let listing = tree.join("crates/llm-gateway/tests/public_listing.rs");
    let source = fs::read_to_string(&listing).unwrap();
    fs::write(&listing, source.replace("fn ", "fn renamed_")).unwrap();
    let out = docs(&["generate", "--root", at]);
    assert!(!out.status.success(), "a vanished test still generated");
    assert!(
        text(&out.stderr).contains("public_listing.rs has no test"),
        "{}",
        text(&out.stderr)
    );
    fs::remove_dir_all(tree).unwrap();
}

#[test]
fn provenance_binds_the_site_to_its_commit_and_lists_its_routes() {
    let site = scratch("provenance");
    let at = site.to_str().unwrap();
    assert!(
        !docs(&["provenance", "--site", at, "--commit", COMMIT])
            .status
            .success(),
        "a directory with no built site is refused"
    );
    fs::create_dir_all(site.join("docs/status")).unwrap();
    fs::write(site.join("index.html"), r#"<main id="main">"#).unwrap();
    fs::write(site.join("docs.html"), r#"<h1 id="llm-gateway">"#).unwrap();
    fs::write(site.join("docs/status.html"), r#"<h2 id="shipped">"#).unwrap();
    fs::write(
        site.join("docs/status/index.html"),
        r#"<!-- b10x-trailing-slash-copy --><h2 id="shipped">"#,
    )
    .unwrap();
    fs::write(site.join("404.html"), r#"<main id="lost">"#).unwrap();
    for bad in ["e86f43d", "0000000000000000000000000000000000000000"] {
        assert!(
            !docs(&["provenance", "--site", at, "--commit", bad])
                .status
                .success(),
            "commit {bad} is refused"
        );
    }
    let out = docs(&["provenance", "--site", at, "--commit", COMMIT]);
    assert!(out.status.success(), "{}", text(&out.stderr));
    let manifest: serde_json::Value =
        serde_json::from_str(&read(&site, ".well-known/b10x-site.json")).unwrap();
    assert_eq!(manifest["schema"], "b10x-project-site/v1");
    assert_eq!(manifest["repository"], "llm-gateway");
    assert_eq!(manifest["baseUrl"], "/llm-gateway/");
    assert_eq!(manifest["commit"], COMMIT);
    assert!(site.join(".nojekyll").is_file());
    let routes: serde_json::Value =
        serde_json::from_str(&read(&site, ".well-known/b10x-routes.json")).unwrap();
    assert_eq!(routes["schema"], "b10x-project-routes/v1");
    assert_eq!(routes["repository"], "llm-gateway");
    assert_eq!(routes["commit"], COMMIT);
    let paths: Vec<_> = routes["routes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|route| route["path"].as_str().unwrap())
        .collect();
    assert_eq!(
        paths,
        [
            "/llm-gateway/",
            "/llm-gateway/docs/",
            "/llm-gateway/docs/status/"
        ]
    );
    fs::remove_dir_all(site).unwrap();
}
