import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {withProductSite} from '@beyond10x/docs-system/product-site';

// `docs/reference/cli.md`, `docs/reference/crates.md`, `docs/reference/refusals.md`,
// `docs/status.mdx` and `data/status.json` are generated by `llm-gateway-docs generate`;
// everything else is written by hand.
const config: Config = {
  title: 'llm-gateway',
  tagline: 'One authenticated gateway for one owner, in front of the models it serves.',
  favicon: 'img/mark.svg',

  future: {
    v4: true,
  },

  url: 'https://beyond10x.github.io',
  baseUrl: '/llm-gateway/',

  organizationName: 'beyond10x',
  projectName: 'llm-gateway',
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'docs',
          editUrl: 'https://github.com/beyond10x/llm-gateway/tree/main/website/',
        },
        blog: false,
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'llm-gateway',
      items: [
        {to: '/docs/', label: 'Documentation', position: 'left'},
        {to: '/docs/reference/cli', label: 'Reference', position: 'left'},
        {to: '/docs/status', label: 'Status', position: 'left'},
        {href: 'https://github.com/beyond10x/llm-gateway', label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      links: [
        {
          title: 'Documentation',
          items: [
            {label: 'Overview', to: '/docs/'},
            {label: 'Getting started', to: '/docs/getting-started'},
            {label: 'The single-owner gateway', to: '/docs/concepts/single-owner-gateway'},
            {label: 'Status', to: '/docs/status'},
          ],
        },
        {
          title: 'Guides',
          items: [
            {label: 'Set up a client', to: '/docs/guides/set-up-a-client'},
            {label: 'Scrape the counters', to: '/docs/guides/scrape-the-counters'},
            {label: 'Run the checks', to: '/docs/guides/run-the-checks'},
          ],
        },
        {
          title: 'Project',
          items: [
            {label: 'Source', href: 'https://github.com/beyond10x/llm-gateway'},
            {label: 'Releases', href: 'https://github.com/beyond10x/llm-gateway/releases'},
          ],
        },
      ],
      copyright: 'A beyond10x project. llm-gateway · Apache-2.0.',
    },
  } satisfies Preset.ThemeConfig,
};

export default withProductSite(config, {landing: './product.json', mark: 'GW'});
